// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: waitroom.proto

package waitroom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WaitroomService_JoinQueue_FullMethodName           = "/waitroom.v1.WaitroomService/JoinQueue"
	WaitroomService_GetQueueStatus_FullMethodName      = "/waitroom.v1.WaitroomService/GetQueueStatus"
	WaitroomService_LeaveQueue_FullMethodName          = "/waitroom.v1.WaitroomService/LeaveQueue"
	WaitroomService_StreamQueuePosition_FullMethodName = "/waitroom.v1.WaitroomService/StreamQueuePosition"
	WaitroomService_HealthCheck_FullMethodName         = "/waitroom.v1.WaitroomService/HealthCheck"
)

// WaitroomServiceClient is the client API for WaitroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WaitroomServiceClient interface {
	JoinQueue(ctx context.Context, in *JoinQueueRequest, opts ...grpc.CallOption) (*JoinQueueResponse, error)
	GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*QueueStatusResponse, error)
	LeaveQueue(ctx context.Context, in *LeaveQueueRequest, opts ...grpc.CallOption) (*LeaveQueueResponse, error)
	StreamQueuePosition(ctx context.Context, in *StreamPositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type waitroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWaitroomServiceClient(cc grpc.ClientConnInterface) WaitroomServiceClient {
	return &waitroomServiceClient{cc}
}

func (c *waitroomServiceClient) JoinQueue(ctx context.Context, in *JoinQueueRequest, opts ...grpc.CallOption) (*JoinQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinQueueResponse)
	err := c.cc.Invoke(ctx, WaitroomService_JoinQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waitroomServiceClient) GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*QueueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStatusResponse)
	err := c.cc.Invoke(ctx, WaitroomService_GetQueueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waitroomServiceClient) LeaveQueue(ctx context.Context, in *LeaveQueueRequest, opts ...grpc.CallOption) (*LeaveQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveQueueResponse)
	err := c.cc.Invoke(ctx, WaitroomService_LeaveQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waitroomServiceClient) StreamQueuePosition(ctx context.Context, in *StreamPositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WaitroomService_ServiceDesc.Streams[0], WaitroomService_StreamQueuePosition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPositionRequest, PositionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WaitroomService_StreamQueuePositionClient = grpc.ServerStreamingClient[PositionUpdate]

func (c *waitroomServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WaitroomService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaitroomServiceServer is the server API for WaitroomService service.
// All implementations must embed UnimplementedWaitroomServiceServer
// for forward compatibility.
type WaitroomServiceServer interface {
	JoinQueue(context.Context, *JoinQueueRequest) (*JoinQueueResponse, error)
	GetQueueStatus(context.Context, *GetQueueStatusRequest) (*QueueStatusResponse, error)
	LeaveQueue(context.Context, *LeaveQueueRequest) (*LeaveQueueResponse, error)
	StreamQueuePosition(*StreamPositionRequest, grpc.ServerStreamingServer[PositionUpdate]) error
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedWaitroomServiceServer()
}

// UnimplementedWaitroomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWaitroomServiceServer struct{}

func (UnimplementedWaitroomServiceServer) JoinQueue(context.Context, *JoinQueueRequest) (*JoinQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinQueue not implemented")
}
func (UnimplementedWaitroomServiceServer) GetQueueStatus(context.Context, *GetQueueStatusRequest) (*QueueStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueStatus not implemented")
}
func (UnimplementedWaitroomServiceServer) LeaveQueue(context.Context, *LeaveQueueRequest) (*LeaveQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveQueue not implemented")
}
func (UnimplementedWaitroomServiceServer) StreamQueuePosition(*StreamPositionRequest, grpc.ServerStreamingServer[PositionUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamQueuePosition not implemented")
}
func (UnimplementedWaitroomServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWaitroomServiceServer) mustEmbedUnimplementedWaitroomServiceServer() {}
func (UnimplementedWaitroomServiceServer) testEmbeddedByValue()                         {}

// UnsafeWaitroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WaitroomServiceServer will
// result in compilation errors.
type UnsafeWaitroomServiceServer interface {
	mustEmbedUnimplementedWaitroomServiceServer()
}

func RegisterWaitroomServiceServer(s grpc.ServiceRegistrar, srv WaitroomServiceServer) {
	// If the following call pancis, it indicates UnimplementedWaitroomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WaitroomService_ServiceDesc, srv)
}

func _WaitroomService_JoinQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaitroomServiceServer).JoinQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaitroomService_JoinQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaitroomServiceServer).JoinQueue(ctx, req.(*JoinQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaitroomService_GetQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaitroomServiceServer).GetQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaitroomService_GetQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaitroomServiceServer).GetQueueStatus(ctx, req.(*GetQueueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaitroomService_LeaveQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaitroomServiceServer).LeaveQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaitroomService_LeaveQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaitroomServiceServer).LeaveQueue(ctx, req.(*LeaveQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaitroomService_StreamQueuePosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WaitroomServiceServer).StreamQueuePosition(m, &grpc.GenericServerStream[StreamPositionRequest, PositionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WaitroomService_StreamQueuePositionServer = grpc.ServerStreamingServer[PositionUpdate]

func _WaitroomService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaitroomServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaitroomService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaitroomServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WaitroomService_ServiceDesc is the grpc.ServiceDesc for WaitroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WaitroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "waitroom.v1.WaitroomService",
	HandlerType: (*WaitroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinQueue",
			Handler:    _WaitroomService_JoinQueue_Handler,
		},
		{
			MethodName: "GetQueueStatus",
			Handler:    _WaitroomService_GetQueueStatus_Handler,
		},
		{
			MethodName: "LeaveQueue",
			Handler:    _WaitroomService_LeaveQueue_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WaitroomService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamQueuePosition",
			Handler:       _WaitroomService_StreamQueuePosition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "waitroom.proto",
}
