// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: waitroom.proto

package waitroom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_QUEUED      SessionStatus = 1
	SessionStatus_SESSION_STATUS_PROCESSING  SessionStatus = 2
	SessionStatus_SESSION_STATUS_READY       SessionStatus = 3
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 4
	SessionStatus_SESSION_STATUS_COMPLETED   SessionStatus = 5
	SessionStatus_SESSION_STATUS_FAILED      SessionStatus = 6
	SessionStatus_SESSION_STATUS_EXPIRED     SessionStatus = 7
	SessionStatus_SESSION_STATUS_CANCELLED   SessionStatus = 8
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_QUEUED",
		2: "SESSION_STATUS_PROCESSING",
		3: "SESSION_STATUS_READY",
		4: "SESSION_STATUS_ACTIVE",
		5: "SESSION_STATUS_COMPLETED",
		6: "SESSION_STATUS_FAILED",
		7: "SESSION_STATUS_EXPIRED",
		8: "SESSION_STATUS_CANCELLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_QUEUED":      1,
		"SESSION_STATUS_PROCESSING":  2,
		"SESSION_STATUS_READY":       3,
		"SESSION_STATUS_ACTIVE":      4,
		"SESSION_STATUS_COMPLETED":   5,
		"SESSION_STATUS_FAILED":      6,
		"SESSION_STATUS_EXPIRED":     7,
		"SESSION_STATUS_CANCELLED":   8,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_waitroom_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_waitroom_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{0}
}

type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_waitroom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{0}
}

func (x *JoinQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinQueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JoinQueueRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *JoinQueueRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type JoinQueueResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Position             int64                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	QueueLength          int64                  `protobuf:"varint,3,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	EstimatedWaitSeconds int32                  `protobuf:"varint,4,opt,name=estimated_wait_seconds,json=estimatedWaitSeconds,proto3" json:"estimated_wait_seconds,omitempty"`
	QueuedAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	WebsocketUrl         string                 `protobuf:"bytes,7,opt,name=websocket_url,json=websocketUrl,proto3" json:"websocket_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JoinQueueResponse) Reset() {
	*x = JoinQueueResponse{}
	mi := &file_waitroom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueResponse) ProtoMessage() {}

func (x *JoinQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinQueueResponse) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{1}
}

func (x *JoinQueueResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinQueueResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *JoinQueueResponse) GetQueueLength() int64 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *JoinQueueResponse) GetEstimatedWaitSeconds() int32 {
	if x != nil {
		return x.EstimatedWaitSeconds
	}
	return 0
}

func (x *JoinQueueResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *JoinQueueResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *JoinQueueResponse) GetWebsocketUrl() string {
	if x != nil {
		return x.WebsocketUrl
	}
	return ""
}

type GetQueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusRequest) Reset() {
	*x = GetQueueStatusRequest{}
	mi := &file_waitroom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusRequest) ProtoMessage() {}

func (x *GetQueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{2}
}

func (x *GetQueueStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type QueueStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status               SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=waitroom.v1.SessionStatus" json:"status,omitempty"`
	Position             int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	QueueLength          int64                  `protobuf:"varint,4,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	EstimatedWaitSeconds int32                  `protobuf:"varint,5,opt,name=estimated_wait_seconds,json=estimatedWaitSeconds,proto3" json:"estimated_wait_seconds,omitempty"`
	QueuedAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CheckoutToken        string                 `protobuf:"bytes,8,opt,name=checkout_token,json=checkoutToken,proto3" json:"checkout_token,omitempty"`
	CheckoutUrl          string                 `protobuf:"bytes,9,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	CheckoutExpiresAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=checkout_expires_at,json=checkoutExpiresAt,proto3" json:"checkout_expires_at,omitempty"`
	AdmittedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=admitted_at,json=admittedAt,proto3" json:"admitted_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_waitroom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{3}
}

func (x *QueueStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueueStatusResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *QueueStatusResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QueueStatusResponse) GetQueueLength() int64 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *QueueStatusResponse) GetEstimatedWaitSeconds() int32 {
	if x != nil {
		return x.EstimatedWaitSeconds
	}
	return 0
}

func (x *QueueStatusResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *QueueStatusResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *QueueStatusResponse) GetCheckoutToken() string {
	if x != nil {
		return x.CheckoutToken
	}
	return ""
}

func (x *QueueStatusResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *QueueStatusResponse) GetCheckoutExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckoutExpiresAt
	}
	return nil
}

func (x *QueueStatusResponse) GetAdmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AdmittedAt
	}
	return nil
}

type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_waitroom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveQueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LeaveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueResponse) Reset() {
	*x = LeaveQueueResponse{}
	mi := &file_waitroom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueResponse) ProtoMessage() {}

func (x *LeaveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueResponse.ProtoReflect.Descriptor instead.
func (*LeaveQueueResponse) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveQueueResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPositionRequest) Reset() {
	*x = StreamPositionRequest{}
	mi := &file_waitroom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPositionRequest) ProtoMessage() {}

func (x *StreamPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPositionRequest.ProtoReflect.Descriptor instead.
func (*StreamPositionRequest) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{6}
}

func (x *StreamPositionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PositionUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Position             int64                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	QueueLength          int64                  `protobuf:"varint,3,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	EstimatedWaitSeconds int32                  `protobuf:"varint,4,opt,name=estimated_wait_seconds,json=estimatedWaitSeconds,proto3" json:"estimated_wait_seconds,omitempty"`
	Status               SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=waitroom.v1.SessionStatus" json:"status,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CheckoutToken        string                 `protobuf:"bytes,7,opt,name=checkout_token,json=checkoutToken,proto3" json:"checkout_token,omitempty"`
	CheckoutUrl          string                 `protobuf:"bytes,8,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_waitroom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{7}
}

func (x *PositionUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PositionUpdate) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PositionUpdate) GetQueueLength() int64 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *PositionUpdate) GetEstimatedWaitSeconds() int32 {
	if x != nil {
		return x.EstimatedWaitSeconds
	}
	return 0
}

func (x *PositionUpdate) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *PositionUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PositionUpdate) GetCheckoutToken() string {
	if x != nil {
		return x.CheckoutToken
	}
	return ""
}

func (x *PositionUpdate) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_waitroom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	KafkaEnabled  bool                   `protobuf:"varint,4,opt,name=kafka_enabled,json=kafkaEnabled,proto3" json:"kafka_enabled,omitempty"`
	Components    map[string]string      `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_waitroom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waitroom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_waitroom_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetKafkaEnabled() bool {
	if x != nil {
		return x.KafkaEnabled
	}
	return false
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_waitroom_proto protoreflect.FileDescriptor

const file_waitroom_proto_rawDesc = "" +
	"\n" +
	"\x0ewaitroom.proto\x12\vwaitroom.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x10JoinQueueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\"\xc0\x02\n" +
	"\x11JoinQueueResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12!\n" +
	"\fqueue_length\x18\x03 \x01(\x03R\vqueueLength\x124\n" +
	"\x16estimated_wait_seconds\x18\x04 \x01(\x05R\x14estimatedWaitSeconds\x127\n" +
	"\tqueued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rwebsocket_url\x18\a \x01(\tR\fwebsocketUrl\"6\n" +
	"\x15GetQueueStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa4\x04\n" +
	"\x13QueueStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.waitroom.v1.SessionStatusR\x06status\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x12!\n" +
	"\fqueue_length\x18\x04 \x01(\x03R\vqueueLength\x124\n" +
	"\x16estimated_wait_seconds\x18\x05 \x01(\x05R\x14estimatedWaitSeconds\x127\n" +
	"\tqueued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0echeckout_token\x18\b \x01(\tR\rcheckoutToken\x12!\n" +
	"\fcheckout_url\x18\t \x01(\tR\vcheckoutUrl\x12J\n" +
	"\x13checkout_expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x11checkoutExpiresAt\x12;\n" +
	"\vadmitted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"admittedAt\"2\n" +
	"\x11LeaveQueueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"M\n" +
	"\x12LeaveQueueResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x15StreamPositionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xdd\x02\n" +
	"\x0ePositionUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12!\n" +
	"\fqueue_length\x18\x03 \x01(\x03R\vqueueLength\x124\n" +
	"\x16estimated_wait_seconds\x18\x04 \x01(\x05R\x14estimatedWaitSeconds\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.waitroom.v1.SessionStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0echeckout_token\x18\a \x01(\tR\rcheckoutToken\x12!\n" +
	"\fcheckout_url\x18\b \x01(\tR\vcheckoutUrl\"\x14\n" +
	"\x12HealthCheckRequest\"\x97\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rkafka_enabled\x18\x04 \x01(\bR\fkafkaEnabled\x12P\n" +
	"\n" +
	"components\x18\x05 \x03(\v20.waitroom.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x91\x02\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_QUEUED\x10\x01\x12\x1d\n" +
	"\x19SESSION_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_READY\x10\x03\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x05\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x06\x12\x1a\n" +
	"\x16SESSION_STATUS_EXPIRED\x10\a\x12\x1c\n" +
	"\x18SESSION_STATUS_CANCELLED\x10\b2\xb0\x03\n" +
	"\x0fWaitroomService\x12J\n" +
	"\tJoinQueue\x12\x1d.waitroom.v1.JoinQueueRequest\x1a\x1e.waitroom.v1.JoinQueueResponse\x12V\n" +
	"\x0eGetQueueStatus\x12\".waitroom.v1.GetQueueStatusRequest\x1a .waitroom.v1.QueueStatusResponse\x12M\n" +
	"\n" +
	"LeaveQueue\x12\x1e.waitroom.v1.LeaveQueueRequest\x1a\x1f.waitroom.v1.LeaveQueueResponse\x12X\n" +
	"\x13StreamQueuePosition\x12\".waitroom.v1.StreamPositionRequest\x1a\x1b.waitroom.v1.PositionUpdate0\x01\x12P\n" +
	"\vHealthCheck\x12\x1f.waitroom.v1.HealthCheckRequest\x1a .waitroom.v1.HealthCheckResponseBFZDgithub.com/vogiaan1904/ticketbottle-waitroom/proto/waitroom;waitroomb\x06proto3"

var (
	file_waitroom_proto_rawDescOnce sync.Once
	file_waitroom_proto_rawDescData []byte
)

func file_waitroom_proto_rawDescGZIP() []byte {
	file_waitroom_proto_rawDescOnce.Do(func() {
		file_waitroom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waitroom_proto_rawDesc), len(file_waitroom_proto_rawDesc)))
	})
	return file_waitroom_proto_rawDescData
}

var file_waitroom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_waitroom_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_waitroom_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: waitroom.v1.SessionStatus
	(*JoinQueueRequest)(nil),      // 1: waitroom.v1.JoinQueueRequest
	(*JoinQueueResponse)(nil),     // 2: waitroom.v1.JoinQueueResponse
	(*GetQueueStatusRequest)(nil), // 3: waitroom.v1.GetQueueStatusRequest
	(*QueueStatusResponse)(nil),   // 4: waitroom.v1.QueueStatusResponse
	(*LeaveQueueRequest)(nil),     // 5: waitroom.v1.LeaveQueueRequest
	(*LeaveQueueResponse)(nil),    // 6: waitroom.v1.LeaveQueueResponse
	(*StreamPositionRequest)(nil), // 7: waitroom.v1.StreamPositionRequest
	(*PositionUpdate)(nil),        // 8: waitroom.v1.PositionUpdate
	(*HealthCheckRequest)(nil),    // 9: waitroom.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 10: waitroom.v1.HealthCheckResponse
	nil,                           // 11: waitroom.v1.HealthCheckResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_waitroom_proto_depIdxs = []int32{
	12, // 0: waitroom.v1.JoinQueueResponse.queued_at:type_name -> google.protobuf.Timestamp
	12, // 1: waitroom.v1.JoinQueueResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: waitroom.v1.QueueStatusResponse.status:type_name -> waitroom.v1.SessionStatus
	12, // 3: waitroom.v1.QueueStatusResponse.queued_at:type_name -> google.protobuf.Timestamp
	12, // 4: waitroom.v1.QueueStatusResponse.expires_at:type_name -> google.protobuf.Timestamp
	12, // 5: waitroom.v1.QueueStatusResponse.checkout_expires_at:type_name -> google.protobuf.Timestamp
	12, // 6: waitroom.v1.QueueStatusResponse.admitted_at:type_name -> google.protobuf.Timestamp
	0,  // 7: waitroom.v1.PositionUpdate.status:type_name -> waitroom.v1.SessionStatus
	12, // 8: waitroom.v1.PositionUpdate.updated_at:type_name -> google.protobuf.Timestamp
	11, // 9: waitroom.v1.HealthCheckResponse.components:type_name -> waitroom.v1.HealthCheckResponse.ComponentsEntry
	1,  // 10: waitroom.v1.WaitroomService.JoinQueue:input_type -> waitroom.v1.JoinQueueRequest
	3,  // 11: waitroom.v1.WaitroomService.GetQueueStatus:input_type -> waitroom.v1.GetQueueStatusRequest
	5,  // 12: waitroom.v1.WaitroomService.LeaveQueue:input_type -> waitroom.v1.LeaveQueueRequest
	7,  // 13: waitroom.v1.WaitroomService.StreamQueuePosition:input_type -> waitroom.v1.StreamPositionRequest
	9,  // 14: waitroom.v1.WaitroomService.HealthCheck:input_type -> waitroom.v1.HealthCheckRequest
	2,  // 15: waitroom.v1.WaitroomService.JoinQueue:output_type -> waitroom.v1.JoinQueueResponse
	4,  // 16: waitroom.v1.WaitroomService.GetQueueStatus:output_type -> waitroom.v1.QueueStatusResponse
	6,  // 17: waitroom.v1.WaitroomService.LeaveQueue:output_type -> waitroom.v1.LeaveQueueResponse
	8,  // 18: waitroom.v1.WaitroomService.StreamQueuePosition:output_type -> waitroom.v1.PositionUpdate
	10, // 19: waitroom.v1.WaitroomService.HealthCheck:output_type -> waitroom.v1.HealthCheckResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_waitroom_proto_init() }
func file_waitroom_proto_init() {
	if File_waitroom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waitroom_proto_rawDesc), len(file_waitroom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_waitroom_proto_goTypes,
		DependencyIndexes: file_waitroom_proto_depIdxs,
		EnumInfos:         file_waitroom_proto_enumTypes,
		MessageInfos:      file_waitroom_proto_msgTypes,
	}.Build()
	File_waitroom_proto = out.File
	file_waitroom_proto_goTypes = nil
	file_waitroom_proto_depIdxs = nil
}
