// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatus int32

const (
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	EventStatus_EVENT_STATUS_DRAFT       EventStatus = 1
	EventStatus_EVENT_STATUS_PUBLISHED   EventStatus = 2
	EventStatus_EVENT_STATUS_CANCELLED   EventStatus = 3
	EventStatus_EVENT_STATUS_CONFIGURED  EventStatus = 4
	EventStatus_EVENT_STATUS_APPROVED    EventStatus = 5
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "EVENT_STATUS_DRAFT",
		2: "EVENT_STATUS_PUBLISHED",
		3: "EVENT_STATUS_CANCELLED",
		4: "EVENT_STATUS_CONFIGURED",
		5: "EVENT_STATUS_APPROVED",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"EVENT_STATUS_DRAFT":       1,
		"EVENT_STATUS_PUBLISHED":   2,
		"EVENT_STATUS_CANCELLED":   3,
		"EVENT_STATUS_CONFIGURED":  4,
		"EVENT_STATUS_APPROVED":    5,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type EventRoleType int32

const (
	EventRoleType_EVENT_ROLE_TYPE_UNSPECIFIED EventRoleType = 0
	EventRoleType_EVENT_ROLE_TYPE_ADMIN       EventRoleType = 1
	EventRoleType_EVENT_ROLE_TYPE_EDITOR      EventRoleType = 2
	EventRoleType_EVENT_ROLE_TYPE_VIEWER      EventRoleType = 3
)

// Enum value maps for EventRoleType.
var (
	EventRoleType_name = map[int32]string{
		0: "EVENT_ROLE_TYPE_UNSPECIFIED",
		1: "EVENT_ROLE_TYPE_ADMIN",
		2: "EVENT_ROLE_TYPE_EDITOR",
		3: "EVENT_ROLE_TYPE_VIEWER",
	}
	EventRoleType_value = map[string]int32{
		"EVENT_ROLE_TYPE_UNSPECIFIED": 0,
		"EVENT_ROLE_TYPE_ADMIN":       1,
		"EVENT_ROLE_TYPE_EDITOR":      2,
		"EVENT_ROLE_TYPE_VIEWER":      3,
	}
)

func (x EventRoleType) Enum() *EventRoleType {
	p := new(EventRoleType)
	*p = x
	return p
}

func (x EventRoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventRoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventRoleType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventRoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventRoleType.Descriptor instead.
func (EventRoleType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Location      *EventLocation         `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Config        *EventConfig           `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	Organizer     *EventOrganizer        `protobuf:"bytes,9,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Roles         []*EventRole           `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	Categories    []*EventCategory       `protobuf:"bytes,11,rep,name=categories,proto3" json:"categories,omitempty"`
	Status        EventStatus            `protobuf:"varint,12,opt,name=status,proto3,enum=event.EventStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Event) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Event) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Event) GetLocation() *EventLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Event) GetConfig() *EventConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Event) GetOrganizer() *EventOrganizer {
	if x != nil {
		return x.Organizer
	}
	return nil
}

func (x *Event) GetRoles() []*EventRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Event) GetCategories() []*EventCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Event) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EventCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCategory) Reset() {
	*x = EventCategory{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCategory) ProtoMessage() {}

func (x *EventCategory) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCategory.ProtoReflect.Descriptor instead.
func (*EventCategory) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketSaleStartDate string                 `protobuf:"bytes,2,opt,name=ticket_sale_start_date,json=ticketSaleStartDate,proto3" json:"ticket_sale_start_date,omitempty"`
	TicketSaleEndDate   string                 `protobuf:"bytes,3,opt,name=ticket_sale_end_date,json=ticketSaleEndDate,proto3" json:"ticket_sale_end_date,omitempty"`
	IsFree              bool                   `protobuf:"varint,4,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	MaxAttendees        int32                  `protobuf:"varint,5,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	IsPublic            bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	RequiresApproval    bool                   `protobuf:"varint,7,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	AllowWaitRoom       bool                   `protobuf:"varint,8,opt,name=allow_wait_room,json=allowWaitRoom,proto3" json:"allow_wait_room,omitempty"`
	IsNewTrending       bool                   `protobuf:"varint,9,opt,name=is_new_trending,json=isNewTrending,proto3" json:"is_new_trending,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventConfig) Reset() {
	*x = EventConfig{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventConfig) ProtoMessage() {}

func (x *EventConfig) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventConfig.ProtoReflect.Descriptor instead.
func (*EventConfig) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventConfig) GetTicketSaleStartDate() string {
	if x != nil {
		return x.TicketSaleStartDate
	}
	return ""
}

func (x *EventConfig) GetTicketSaleEndDate() string {
	if x != nil {
		return x.TicketSaleEndDate
	}
	return ""
}

func (x *EventConfig) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *EventConfig) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventConfig) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *EventConfig) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *EventConfig) GetAllowWaitRoom() bool {
	if x != nil {
		return x.AllowWaitRoom
	}
	return false
}

func (x *EventConfig) GetIsNewTrending() bool {
	if x != nil {
		return x.IsNewTrending
	}
	return false
}

type EventLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Venue         string                 `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLocation) Reset() {
	*x = EventLocation{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLocation) ProtoMessage() {}

func (x *EventLocation) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLocation.ProtoReflect.Descriptor instead.
func (*EventLocation) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *EventLocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventLocation) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *EventLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EventOrganizer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOrganizer) Reset() {
	*x = EventOrganizer{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOrganizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOrganizer) ProtoMessage() {}

func (x *EventOrganizer) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOrganizer.ProtoReflect.Descriptor instead.
func (*EventOrganizer) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventOrganizer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventOrganizer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventOrganizer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventOrganizer) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type EventRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Role          EventRoleType          `protobuf:"varint,4,opt,name=role,proto3,enum=event.EventRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRole) Reset() {
	*x = EventRole{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRole) ProtoMessage() {}

func (x *EventRole) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRole.ProtoReflect.Descriptor instead.
func (*EventRole) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *EventRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventRole) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventRole) GetRole() EventRoleType {
	if x != nil {
		return x.Role
	}
	return EventRoleType_EVENT_ROLE_TYPE_UNSPECIFIED
}

type CreateEventRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartDate            string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ThumbnailUrl         string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Venue                string                 `protobuf:"bytes,6,opt,name=venue,proto3" json:"venue,omitempty"`
	Street               string                 `protobuf:"bytes,7,opt,name=street,proto3" json:"street,omitempty"`
	City                 string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Country              string                 `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Ward                 *string                `protobuf:"bytes,10,opt,name=ward,proto3,oneof" json:"ward,omitempty"`
	District             *string                `protobuf:"bytes,11,opt,name=district,proto3,oneof" json:"district,omitempty"`
	CategoryIds          []string               `protobuf:"bytes,12,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	OrganizerName        string                 `protobuf:"bytes,13,opt,name=organizer_name,json=organizerName,proto3" json:"organizer_name,omitempty"`
	OrganizerDescription string                 `protobuf:"bytes,14,opt,name=organizer_description,json=organizerDescription,proto3" json:"organizer_description,omitempty"`
	OrganizerLogoUrl     string                 `protobuf:"bytes,15,opt,name=organizer_logo_url,json=organizerLogoUrl,proto3" json:"organizer_logo_url,omitempty"`
	CreatorUserId        string                 `protobuf:"bytes,16,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateEventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateEventRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CreateEventRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *CreateEventRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateEventRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateEventRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateEventRequest) GetWard() string {
	if x != nil && x.Ward != nil {
		return *x.Ward
	}
	return ""
}

func (x *CreateEventRequest) GetDistrict() string {
	if x != nil && x.District != nil {
		return *x.District
	}
	return ""
}

func (x *CreateEventRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CreateEventRequest) GetOrganizerName() string {
	if x != nil {
		return x.OrganizerName
	}
	return ""
}

func (x *CreateEventRequest) GetOrganizerDescription() string {
	if x != nil {
		return x.OrganizerDescription
	}
	return ""
}

func (x *CreateEventRequest) GetOrganizerLogoUrl() string {
	if x != nil {
		return x.OrganizerLogoUrl
	}
	return ""
}

func (x *CreateEventRequest) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description          *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StartDate            *string                `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate              *string                `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ThumbnailUrl         *string                `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	VenueName            *string                `protobuf:"bytes,7,opt,name=venue_name,json=venueName,proto3,oneof" json:"venue_name,omitempty"`
	Street               *string                `protobuf:"bytes,8,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City                 *string                `protobuf:"bytes,9,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Country              *string                `protobuf:"bytes,10,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Ward                 *string                `protobuf:"bytes,11,opt,name=ward,proto3,oneof" json:"ward,omitempty"`
	District             *string                `protobuf:"bytes,12,opt,name=district,proto3,oneof" json:"district,omitempty"`
	CategoryIds          []string               `protobuf:"bytes,13,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	OrganizerName        *string                `protobuf:"bytes,14,opt,name=organizer_name,json=organizerName,proto3,oneof" json:"organizer_name,omitempty"`
	OrganizerDescription *string                `protobuf:"bytes,15,opt,name=organizer_description,json=organizerDescription,proto3,oneof" json:"organizer_description,omitempty"`
	OrganizerLogoUrl     *string                `protobuf:"bytes,16,opt,name=organizer_logo_url,json=organizerLogoUrl,proto3,oneof" json:"organizer_logo_url,omitempty"`
	UserId               string                 `protobuf:"bytes,17,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateEventRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *UpdateEventRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateEventRequest) GetVenueName() string {
	if x != nil && x.VenueName != nil {
		return *x.VenueName
	}
	return ""
}

func (x *UpdateEventRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdateEventRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateEventRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateEventRequest) GetWard() string {
	if x != nil && x.Ward != nil {
		return *x.Ward
	}
	return ""
}

func (x *UpdateEventRequest) GetDistrict() string {
	if x != nil && x.District != nil {
		return *x.District
	}
	return ""
}

func (x *UpdateEventRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *UpdateEventRequest) GetOrganizerName() string {
	if x != nil && x.OrganizerName != nil {
		return *x.OrganizerName
	}
	return ""
}

func (x *UpdateEventRequest) GetOrganizerDescription() string {
	if x != nil && x.OrganizerDescription != nil {
		return *x.OrganizerDescription
	}
	return ""
}

func (x *UpdateEventRequest) GetOrganizerLogoUrl() string {
	if x != nil && x.OrganizerLogoUrl != nil {
		return *x.OrganizerLogoUrl
	}
	return ""
}

func (x *UpdateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type FindOneEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneEventRequest) Reset() {
	*x = FindOneEventRequest{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneEventRequest) ProtoMessage() {}

func (x *FindOneEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneEventRequest.ProtoReflect.Descriptor instead.
func (*FindOneEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *FindOneEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOneEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneEventResponse) Reset() {
	*x = FindOneEventResponse{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneEventResponse) ProtoMessage() {}

func (x *FindOneEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneEventResponse.ProtoReflect.Descriptor instead.
func (*FindOneEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *FindOneEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   *string                `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3,oneof" json:"search_query,omitempty"`
	CategoryIds   []string               `protobuf:"bytes,2,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	Status        *EventStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=event.EventStatus,oneof" json:"status,omitempty"`
	OrganizerId   *string                `protobuf:"bytes,4,opt,name=organizer_id,json=organizerId,proto3,oneof" json:"organizer_id,omitempty"`
	UserId        *string                `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	StartDateFrom *string                `protobuf:"bytes,6,opt,name=start_date_from,json=startDateFrom,proto3,oneof" json:"start_date_from,omitempty"`
	StartDateTo   *string                `protobuf:"bytes,7,opt,name=start_date_to,json=startDateTo,proto3,oneof" json:"start_date_to,omitempty"`
	City          *string                `protobuf:"bytes,8,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Country       *string                `protobuf:"bytes,9,opt,name=country,proto3,oneof" json:"country,omitempty"`
	IsPublic      *bool                  `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3,oneof" json:"is_public,omitempty"`
	IsFree        *bool                  `protobuf:"varint,11,opt,name=is_free,json=isFree,proto3,oneof" json:"is_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *EventFilter) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

func (x *EventFilter) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *EventFilter) GetStatus() EventStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *EventFilter) GetOrganizerId() string {
	if x != nil && x.OrganizerId != nil {
		return *x.OrganizerId
	}
	return ""
}

func (x *EventFilter) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *EventFilter) GetStartDateFrom() string {
	if x != nil && x.StartDateFrom != nil {
		return *x.StartDateFrom
	}
	return ""
}

func (x *EventFilter) GetStartDateTo() string {
	if x != nil && x.StartDateTo != nil {
		return *x.StartDateTo
	}
	return ""
}

func (x *EventFilter) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *EventFilter) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *EventFilter) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *EventFilter) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

type FindManyEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        *EventFilter           `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindManyEventRequest) Reset() {
	*x = FindManyEventRequest{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindManyEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyEventRequest) ProtoMessage() {}

func (x *FindManyEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyEventRequest.ProtoReflect.Descriptor instead.
func (*FindManyEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *FindManyEventRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindManyEventRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindManyEventRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type FindManyEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindManyEventResponse) Reset() {
	*x = FindManyEventResponse{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindManyEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyEventResponse) ProtoMessage() {}

func (x *FindManyEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyEventResponse.ProtoReflect.Descriptor instead.
func (*FindManyEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *FindManyEventResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *FindManyEventResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	LastPage      int32                  `protobuf:"varint,4,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	Total         int64                  `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *PaginationInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PaginationInfo) GetLastPage() int32 {
	if x != nil {
		return x.LastPage
	}
	return 0
}

func (x *PaginationInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationInfo) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

type ListEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *EventFilter           `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventRequest) Reset() {
	*x = ListEventRequest{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventRequest) ProtoMessage() {}

func (x *ListEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventRequest.ProtoReflect.Descriptor instead.
func (*ListEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *ListEventRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventResponse) Reset() {
	*x = ListEventResponse{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventResponse) ProtoMessage() {}

func (x *ListEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventResponse.ProtoReflect.Descriptor instead.
func (*ListEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *ListEventResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Event Config messages
type CreateEventConfigRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId             string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketSaleStartDate string                 `protobuf:"bytes,3,opt,name=ticket_sale_start_date,json=ticketSaleStartDate,proto3" json:"ticket_sale_start_date,omitempty"`
	TicketSaleEndDate   string                 `protobuf:"bytes,4,opt,name=ticket_sale_end_date,json=ticketSaleEndDate,proto3" json:"ticket_sale_end_date,omitempty"`
	IsFree              bool                   `protobuf:"varint,5,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	MaxAttendees        int32                  `protobuf:"varint,6,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	IsPublic            bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	RequiresApproval    bool                   `protobuf:"varint,8,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	AllowWaitRoom       bool                   `protobuf:"varint,9,opt,name=allow_wait_room,json=allowWaitRoom,proto3" json:"allow_wait_room,omitempty"`
	IsNewTrending       bool                   `protobuf:"varint,10,opt,name=is_new_trending,json=isNewTrending,proto3" json:"is_new_trending,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateEventConfigRequest) Reset() {
	*x = CreateEventConfigRequest{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventConfigRequest) ProtoMessage() {}

func (x *CreateEventConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateEventConfigRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *CreateEventConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEventConfigRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateEventConfigRequest) GetTicketSaleStartDate() string {
	if x != nil {
		return x.TicketSaleStartDate
	}
	return ""
}

func (x *CreateEventConfigRequest) GetTicketSaleEndDate() string {
	if x != nil {
		return x.TicketSaleEndDate
	}
	return ""
}

func (x *CreateEventConfigRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *CreateEventConfigRequest) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *CreateEventConfigRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreateEventConfigRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *CreateEventConfigRequest) GetAllowWaitRoom() bool {
	if x != nil {
		return x.AllowWaitRoom
	}
	return false
}

func (x *CreateEventConfigRequest) GetIsNewTrending() bool {
	if x != nil {
		return x.IsNewTrending
	}
	return false
}

type CreateEventConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventConfig   *EventConfig           `protobuf:"bytes,1,opt,name=event_config,json=eventConfig,proto3" json:"event_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventConfigResponse) Reset() {
	*x = CreateEventConfigResponse{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventConfigResponse) ProtoMessage() {}

func (x *CreateEventConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateEventConfigResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *CreateEventConfigResponse) GetEventConfig() *EventConfig {
	if x != nil {
		return x.EventConfig
	}
	return nil
}

type GetEventConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventConfigRequest) Reset() {
	*x = GetEventConfigRequest{}
	mi := &file_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventConfigRequest) ProtoMessage() {}

func (x *GetEventConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventConfigRequest.ProtoReflect.Descriptor instead.
func (*GetEventConfigRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{21}
}

func (x *GetEventConfigRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetEventConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetEventConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventConfig   *EventConfig           `protobuf:"bytes,1,opt,name=event_config,json=eventConfig,proto3" json:"event_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventConfigResponse) Reset() {
	*x = GetEventConfigResponse{}
	mi := &file_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventConfigResponse) ProtoMessage() {}

func (x *GetEventConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventConfigResponse.ProtoReflect.Descriptor instead.
func (*GetEventConfigResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{22}
}

func (x *GetEventConfigResponse) GetEventConfig() *EventConfig {
	if x != nil {
		return x.EventConfig
	}
	return nil
}

type UpdateEventConfigRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventId             string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TicketSaleStartDate string                 `protobuf:"bytes,3,opt,name=ticket_sale_start_date,json=ticketSaleStartDate,proto3" json:"ticket_sale_start_date,omitempty"`
	TicketSaleEndDate   string                 `protobuf:"bytes,4,opt,name=ticket_sale_end_date,json=ticketSaleEndDate,proto3" json:"ticket_sale_end_date,omitempty"`
	IsFree              bool                   `protobuf:"varint,5,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	MaxAttendees        int32                  `protobuf:"varint,6,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	IsPublic            bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	RequiresApproval    bool                   `protobuf:"varint,8,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	AllowWaitRoom       bool                   `protobuf:"varint,9,opt,name=allow_wait_room,json=allowWaitRoom,proto3" json:"allow_wait_room,omitempty"`
	IsNewTrending       bool                   `protobuf:"varint,10,opt,name=is_new_trending,json=isNewTrending,proto3" json:"is_new_trending,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateEventConfigRequest) Reset() {
	*x = UpdateEventConfigRequest{}
	mi := &file_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventConfigRequest) ProtoMessage() {}

func (x *UpdateEventConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventConfigRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateEventConfigRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEventConfigRequest) GetTicketSaleStartDate() string {
	if x != nil {
		return x.TicketSaleStartDate
	}
	return ""
}

func (x *UpdateEventConfigRequest) GetTicketSaleEndDate() string {
	if x != nil {
		return x.TicketSaleEndDate
	}
	return ""
}

func (x *UpdateEventConfigRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *UpdateEventConfigRequest) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *UpdateEventConfigRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *UpdateEventConfigRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *UpdateEventConfigRequest) GetAllowWaitRoom() bool {
	if x != nil {
		return x.AllowWaitRoom
	}
	return false
}

func (x *UpdateEventConfigRequest) GetIsNewTrending() bool {
	if x != nil {
		return x.IsNewTrending
	}
	return false
}

type UpdateEventConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventConfig   *EventConfig           `protobuf:"bytes,1,opt,name=event_config,json=eventConfig,proto3" json:"event_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventConfigResponse) Reset() {
	*x = UpdateEventConfigResponse{}
	mi := &file_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventConfigResponse) ProtoMessage() {}

func (x *UpdateEventConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventConfigResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateEventConfigResponse) GetEventConfig() *EventConfig {
	if x != nil {
		return x.EventConfig
	}
	return nil
}

type ApproveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveEventRequest) Reset() {
	*x = ApproveEventRequest{}
	mi := &file_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveEventRequest) ProtoMessage() {}

func (x *ApproveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveEventRequest.ProtoReflect.Descriptor instead.
func (*ApproveEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{25}
}

func (x *ApproveEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ApproveEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{26}
}

func (x *PublishEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventRequest) Reset() {
	*x = CancelEventRequest{}
	mi := &file_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventRequest) ProtoMessage() {}

func (x *CancelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventRequest.ProtoReflect.Descriptor instead.
func (*CancelEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{27}
}

func (x *CancelEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CancelEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventResponse) Reset() {
	*x = CancelEventResponse{}
	mi := &file_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventResponse) ProtoMessage() {}

func (x *CancelEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventResponse.ProtoReflect.Descriptor instead.
func (*CancelEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{28}
}

func (x *CancelEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRolesRequest) Reset() {
	*x = GetEventRolesRequest{}
	mi := &file_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRolesRequest) ProtoMessage() {}

func (x *GetEventRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRolesRequest.ProtoReflect.Descriptor instead.
func (*GetEventRolesRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{29}
}

func (x *GetEventRolesRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*EventRole           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRolesResponse) Reset() {
	*x = GetEventRolesResponse{}
	mi := &file_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRolesResponse) ProtoMessage() {}

func (x *GetEventRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRolesResponse.ProtoReflect.Descriptor instead.
func (*GetEventRolesResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{30}
}

func (x *GetEventRolesResponse) GetRoles() []*EventRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignEventRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          EventRoleType          `protobuf:"varint,3,opt,name=role,proto3,enum=event.EventRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignEventRoleRequest) Reset() {
	*x = AssignEventRoleRequest{}
	mi := &file_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignEventRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignEventRoleRequest) ProtoMessage() {}

func (x *AssignEventRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignEventRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignEventRoleRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{31}
}

func (x *AssignEventRoleRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AssignEventRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignEventRoleRequest) GetRole() EventRoleType {
	if x != nil {
		return x.Role
	}
	return EventRoleType_EVENT_ROLE_TYPE_UNSPECIFIED
}

type AssignEventRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *EventRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignEventRoleResponse) Reset() {
	*x = AssignEventRoleResponse{}
	mi := &file_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignEventRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignEventRoleResponse) ProtoMessage() {}

func (x *AssignEventRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignEventRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignEventRoleResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{32}
}

func (x *AssignEventRoleResponse) GetRole() *EventRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type RemoveEventRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventRoleRequest) Reset() {
	*x = RemoveEventRoleRequest{}
	mi := &file_event_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventRoleRequest) ProtoMessage() {}

func (x *RemoveEventRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveEventRoleRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{33}
}

func (x *RemoveEventRoleRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RemoveEventRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\x1a\x1bgoogle/protobuf/empty.proto\"\x87\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x120\n" +
	"\blocation\x18\a \x01(\v2\x14.event.EventLocationR\blocation\x12*\n" +
	"\x06config\x18\b \x01(\v2\x12.event.EventConfigR\x06config\x123\n" +
	"\torganizer\x18\t \x01(\v2\x15.event.EventOrganizerR\torganizer\x12&\n" +
	"\x05roles\x18\n" +
	" \x03(\v2\x10.event.EventRoleR\x05roles\x124\n" +
	"\n" +
	"categories\x18\v \x03(\v2\x14.event.EventCategoryR\n" +
	"categories\x12*\n" +
	"\x06status\x18\f \x01(\x0e2\x12.event.EventStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"3\n" +
	"\rEventCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xdb\x02\n" +
	"\vEventConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x16ticket_sale_start_date\x18\x02 \x01(\tR\x13ticketSaleStartDate\x12/\n" +
	"\x14ticket_sale_end_date\x18\x03 \x01(\tR\x11ticketSaleEndDate\x12\x17\n" +
	"\ais_free\x18\x04 \x01(\bR\x06isFree\x12#\n" +
	"\rmax_attendees\x18\x05 \x01(\x05R\fmaxAttendees\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x12+\n" +
	"\x11requires_approval\x18\a \x01(\bR\x10requiresApproval\x12&\n" +
	"\x0fallow_wait_room\x18\b \x01(\bR\rallowWaitRoom\x12&\n" +
	"\x0fis_new_trending\x18\t \x01(\bR\risNewTrending\"O\n" +
	"\rEventLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05venue\x18\x02 \x01(\tR\x05venue\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"q\n" +
	"\x0eEventOrganizer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\"y\n" +
	"\tEventRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12(\n" +
	"\x04role\x18\x04 \x01(\x0e2\x14.event.EventRoleTypeR\x04role\"\xaa\x04\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12\x14\n" +
	"\x05venue\x18\x06 \x01(\tR\x05venue\x12\x16\n" +
	"\x06street\x18\a \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\t \x01(\tR\acountry\x12\x17\n" +
	"\x04ward\x18\n" +
	" \x01(\tH\x00R\x04ward\x88\x01\x01\x12\x1f\n" +
	"\bdistrict\x18\v \x01(\tH\x01R\bdistrict\x88\x01\x01\x12!\n" +
	"\fcategory_ids\x18\f \x03(\tR\vcategoryIds\x12%\n" +
	"\x0eorganizer_name\x18\r \x01(\tR\rorganizerName\x123\n" +
	"\x15organizer_description\x18\x0e \x01(\tR\x14organizerDescription\x12,\n" +
	"\x12organizer_logo_url\x18\x0f \x01(\tR\x10organizerLogoUrl\x12&\n" +
	"\x0fcreator_user_id\x18\x10 \x01(\tR\rcreatorUserIdB\a\n" +
	"\x05_wardB\v\n" +
	"\t_district\"9\n" +
	"\x13CreateEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\xaa\x06\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tH\x02R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x05 \x01(\tH\x03R\aendDate\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x06 \x01(\tH\x04R\fthumbnailUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"venue_name\x18\a \x01(\tH\x05R\tvenueName\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\b \x01(\tH\x06R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\t \x01(\tH\aR\x04city\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\n" +
	" \x01(\tH\bR\acountry\x88\x01\x01\x12\x17\n" +
	"\x04ward\x18\v \x01(\tH\tR\x04ward\x88\x01\x01\x12\x1f\n" +
	"\bdistrict\x18\f \x01(\tH\n" +
	"R\bdistrict\x88\x01\x01\x12!\n" +
	"\fcategory_ids\x18\r \x03(\tR\vcategoryIds\x12*\n" +
	"\x0eorganizer_name\x18\x0e \x01(\tH\vR\rorganizerName\x88\x01\x01\x128\n" +
	"\x15organizer_description\x18\x0f \x01(\tH\fR\x14organizerDescription\x88\x01\x01\x121\n" +
	"\x12organizer_logo_url\x18\x10 \x01(\tH\rR\x10organizerLogoUrl\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x11 \x01(\tR\x06userIdB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\x10\n" +
	"\x0e_thumbnail_urlB\r\n" +
	"\v_venue_nameB\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_wardB\v\n" +
	"\t_districtB\x11\n" +
	"\x0f_organizer_nameB\x18\n" +
	"\x16_organizer_descriptionB\x15\n" +
	"\x13_organizer_logo_url\"9\n" +
	"\x13UpdateEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"%\n" +
	"\x13FindOneEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x14FindOneEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\xab\x04\n" +
	"\vEventFilter\x12&\n" +
	"\fsearch_query\x18\x01 \x01(\tH\x00R\vsearchQuery\x88\x01\x01\x12!\n" +
	"\fcategory_ids\x18\x02 \x03(\tR\vcategoryIds\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.event.EventStatusH\x01R\x06status\x88\x01\x01\x12&\n" +
	"\forganizer_id\x18\x04 \x01(\tH\x02R\vorganizerId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x05 \x01(\tH\x03R\x06userId\x88\x01\x01\x12+\n" +
	"\x0fstart_date_from\x18\x06 \x01(\tH\x04R\rstartDateFrom\x88\x01\x01\x12'\n" +
	"\rstart_date_to\x18\a \x01(\tH\x05R\vstartDateTo\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\b \x01(\tH\x06R\x04city\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\t \x01(\tH\aR\acountry\x88\x01\x01\x12 \n" +
	"\tis_public\x18\n" +
	" \x01(\bH\bR\bisPublic\x88\x01\x01\x12\x1c\n" +
	"\ais_free\x18\v \x01(\bH\tR\x06isFree\x88\x01\x01B\x0f\n" +
	"\r_search_queryB\t\n" +
	"\a_statusB\x0f\n" +
	"\r_organizer_idB\n" +
	"\n" +
	"\b_user_idB\x12\n" +
	"\x10_start_date_fromB\x10\n" +
	"\x0e_start_date_toB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_countryB\f\n" +
	"\n" +
	"_is_publicB\n" +
	"\n" +
	"\b_is_free\"\x83\x01\n" +
	"\x14FindManyEventRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12/\n" +
	"\x06filter\x18\x03 \x01(\v2\x12.event.EventFilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"t\n" +
	"\x15FindManyEventResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.event.PaginationInfoR\n" +
	"pagination\"\xc8\x01\n" +
	"\x0ePaginationInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x1b\n" +
	"\tlast_page\x18\x04 \x01(\x05R\blastPage\x12\x14\n" +
	"\x05total\x18\a \x01(\x03R\x05total\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\"N\n" +
	"\x10ListEventRequest\x12/\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.event.EventFilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"9\n" +
	"\x11ListEventResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x03\n" +
	"\x18CreateEventConfigRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x123\n" +
	"\x16ticket_sale_start_date\x18\x03 \x01(\tR\x13ticketSaleStartDate\x12/\n" +
	"\x14ticket_sale_end_date\x18\x04 \x01(\tR\x11ticketSaleEndDate\x12\x17\n" +
	"\ais_free\x18\x05 \x01(\bR\x06isFree\x12#\n" +
	"\rmax_attendees\x18\x06 \x01(\x05R\fmaxAttendees\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\x12+\n" +
	"\x11requires_approval\x18\b \x01(\bR\x10requiresApproval\x12&\n" +
	"\x0fallow_wait_room\x18\t \x01(\bR\rallowWaitRoom\x12&\n" +
	"\x0fis_new_trending\x18\n" +
	" \x01(\bR\risNewTrending\"R\n" +
	"\x19CreateEventConfigResponse\x125\n" +
	"\fevent_config\x18\x01 \x01(\v2\x12.event.EventConfigR\veventConfig\"K\n" +
	"\x15GetEventConfigRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\x16GetEventConfigResponse\x125\n" +
	"\fevent_config\x18\x01 \x01(\v2\x12.event.EventConfigR\veventConfig\"\x8c\x03\n" +
	"\x18UpdateEventConfigRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\x16ticket_sale_start_date\x18\x03 \x01(\tR\x13ticketSaleStartDate\x12/\n" +
	"\x14ticket_sale_end_date\x18\x04 \x01(\tR\x11ticketSaleEndDate\x12\x17\n" +
	"\ais_free\x18\x05 \x01(\bR\x06isFree\x12#\n" +
	"\rmax_attendees\x18\x06 \x01(\x05R\fmaxAttendees\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\x12+\n" +
	"\x11requires_approval\x18\b \x01(\bR\x10requiresApproval\x12&\n" +
	"\x0fallow_wait_room\x18\t \x01(\bR\rallowWaitRoom\x12&\n" +
	"\x0fis_new_trending\x18\n" +
	" \x01(\bR\risNewTrending\"R\n" +
	"\x19UpdateEventConfigResponse\x125\n" +
	"\fevent_config\x18\x01 \x01(\v2\x12.event.EventConfigR\veventConfig\"I\n" +
	"\x13ApproveEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x13PublishEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12CancelEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"9\n" +
	"\x13CancelEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"1\n" +
	"\x14GetEventRolesRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"?\n" +
	"\x15GetEventRolesResponse\x12&\n" +
	"\x05roles\x18\x01 \x03(\v2\x10.event.EventRoleR\x05roles\"v\n" +
	"\x16AssignEventRoleRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.event.EventRoleTypeR\x04role\"?\n" +
	"\x17AssignEventRoleResponse\x12$\n" +
	"\x04role\x18\x01 \x01(\v2\x10.event.EventRoleR\x04role\"L\n" +
	"\x16RemoveEventRoleRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId*\xb3\x01\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16EVENT_STATUS_PUBLISHED\x10\x02\x12\x1a\n" +
	"\x16EVENT_STATUS_CANCELLED\x10\x03\x12\x1b\n" +
	"\x17EVENT_STATUS_CONFIGURED\x10\x04\x12\x19\n" +
	"\x15EVENT_STATUS_APPROVED\x10\x05*\x83\x01\n" +
	"\rEventRoleType\x12\x1f\n" +
	"\x1bEVENT_ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_ROLE_TYPE_ADMIN\x10\x01\x12\x1a\n" +
	"\x16EVENT_ROLE_TYPE_EDITOR\x10\x02\x12\x1a\n" +
	"\x16EVENT_ROLE_TYPE_VIEWER\x10\x032\xb5\b\n" +
	"\fEventService\x12?\n" +
	"\x06Create\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12?\n" +
	"\x06Update\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x12B\n" +
	"\aFindOne\x12\x1a.event.FindOneEventRequest\x1a\x1b.event.FindOneEventResponse\x12E\n" +
	"\bFindMany\x12\x1b.event.FindManyEventRequest\x1a\x1c.event.FindManyEventResponse\x129\n" +
	"\x04List\x12\x17.event.ListEventRequest\x1a\x18.event.ListEventResponse\x12;\n" +
	"\x06Delete\x12\x19.event.DeleteEventRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\fCreateConfig\x12\x1f.event.CreateEventConfigRequest\x1a .event.CreateEventConfigResponse\x12H\n" +
	"\tGetConfig\x12\x1c.event.GetEventConfigRequest\x1a\x1d.event.GetEventConfigResponse\x12Q\n" +
	"\fUpdateConfig\x12\x1f.event.UpdateEventConfigRequest\x1a .event.UpdateEventConfigResponse\x12B\n" +
	"\fApproveEvent\x12\x1a.event.ApproveEventRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\fPublishEvent\x12\x1a.event.PublishEventRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vCancelEvent\x12\x19.event.CancelEventRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\rGetEventRoles\x12\x1b.event.GetEventRolesRequest\x1a\x1c.event.GetEventRolesResponse\x12P\n" +
	"\x0fAssignEventRole\x12\x1d.event.AssignEventRoleRequest\x1a\x1e.event.AssignEventRoleResponse\x12H\n" +
	"\x0fRemoveEventRole\x12\x1d.event.RemoveEventRoleRequest\x1a\x16.google.protobuf.EmptyB7Z5github.com/vogiaan1904/ticketbottle-proto/proto/eventb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_event_proto_goTypes = []any{
	(EventStatus)(0),                  // 0: event.EventStatus
	(EventRoleType)(0),                // 1: event.EventRoleType
	(*Event)(nil),                     // 2: event.Event
	(*EventCategory)(nil),             // 3: event.EventCategory
	(*EventConfig)(nil),               // 4: event.EventConfig
	(*EventLocation)(nil),             // 5: event.EventLocation
	(*EventOrganizer)(nil),            // 6: event.EventOrganizer
	(*EventRole)(nil),                 // 7: event.EventRole
	(*CreateEventRequest)(nil),        // 8: event.CreateEventRequest
	(*CreateEventResponse)(nil),       // 9: event.CreateEventResponse
	(*UpdateEventRequest)(nil),        // 10: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),       // 11: event.UpdateEventResponse
	(*FindOneEventRequest)(nil),       // 12: event.FindOneEventRequest
	(*FindOneEventResponse)(nil),      // 13: event.FindOneEventResponse
	(*EventFilter)(nil),               // 14: event.EventFilter
	(*FindManyEventRequest)(nil),      // 15: event.FindManyEventRequest
	(*FindManyEventResponse)(nil),     // 16: event.FindManyEventResponse
	(*PaginationInfo)(nil),            // 17: event.PaginationInfo
	(*ListEventRequest)(nil),          // 18: event.ListEventRequest
	(*ListEventResponse)(nil),         // 19: event.ListEventResponse
	(*DeleteEventRequest)(nil),        // 20: event.DeleteEventRequest
	(*CreateEventConfigRequest)(nil),  // 21: event.CreateEventConfigRequest
	(*CreateEventConfigResponse)(nil), // 22: event.CreateEventConfigResponse
	(*GetEventConfigRequest)(nil),     // 23: event.GetEventConfigRequest
	(*GetEventConfigResponse)(nil),    // 24: event.GetEventConfigResponse
	(*UpdateEventConfigRequest)(nil),  // 25: event.UpdateEventConfigRequest
	(*UpdateEventConfigResponse)(nil), // 26: event.UpdateEventConfigResponse
	(*ApproveEventRequest)(nil),       // 27: event.ApproveEventRequest
	(*PublishEventRequest)(nil),       // 28: event.PublishEventRequest
	(*CancelEventRequest)(nil),        // 29: event.CancelEventRequest
	(*CancelEventResponse)(nil),       // 30: event.CancelEventResponse
	(*GetEventRolesRequest)(nil),      // 31: event.GetEventRolesRequest
	(*GetEventRolesResponse)(nil),     // 32: event.GetEventRolesResponse
	(*AssignEventRoleRequest)(nil),    // 33: event.AssignEventRoleRequest
	(*AssignEventRoleResponse)(nil),   // 34: event.AssignEventRoleResponse
	(*RemoveEventRoleRequest)(nil),    // 35: event.RemoveEventRoleRequest
	(*emptypb.Empty)(nil),             // 36: google.protobuf.Empty
}
var file_event_proto_depIdxs = []int32{
	5,  // 0: event.Event.location:type_name -> event.EventLocation
	4,  // 1: event.Event.config:type_name -> event.EventConfig
	6,  // 2: event.Event.organizer:type_name -> event.EventOrganizer
	7,  // 3: event.Event.roles:type_name -> event.EventRole
	3,  // 4: event.Event.categories:type_name -> event.EventCategory
	0,  // 5: event.Event.status:type_name -> event.EventStatus
	1,  // 6: event.EventRole.role:type_name -> event.EventRoleType
	2,  // 7: event.CreateEventResponse.event:type_name -> event.Event
	2,  // 8: event.UpdateEventResponse.event:type_name -> event.Event
	2,  // 9: event.FindOneEventResponse.event:type_name -> event.Event
	0,  // 10: event.EventFilter.status:type_name -> event.EventStatus
	14, // 11: event.FindManyEventRequest.filter:type_name -> event.EventFilter
	2,  // 12: event.FindManyEventResponse.events:type_name -> event.Event
	17, // 13: event.FindManyEventResponse.pagination:type_name -> event.PaginationInfo
	14, // 14: event.ListEventRequest.filter:type_name -> event.EventFilter
	2,  // 15: event.ListEventResponse.events:type_name -> event.Event
	4,  // 16: event.CreateEventConfigResponse.event_config:type_name -> event.EventConfig
	4,  // 17: event.GetEventConfigResponse.event_config:type_name -> event.EventConfig
	4,  // 18: event.UpdateEventConfigResponse.event_config:type_name -> event.EventConfig
	2,  // 19: event.CancelEventResponse.event:type_name -> event.Event
	7,  // 20: event.GetEventRolesResponse.roles:type_name -> event.EventRole
	1,  // 21: event.AssignEventRoleRequest.role:type_name -> event.EventRoleType
	7,  // 22: event.AssignEventRoleResponse.role:type_name -> event.EventRole
	8,  // 23: event.EventService.Create:input_type -> event.CreateEventRequest
	10, // 24: event.EventService.Update:input_type -> event.UpdateEventRequest
	12, // 25: event.EventService.FindOne:input_type -> event.FindOneEventRequest
	15, // 26: event.EventService.FindMany:input_type -> event.FindManyEventRequest
	18, // 27: event.EventService.List:input_type -> event.ListEventRequest
	20, // 28: event.EventService.Delete:input_type -> event.DeleteEventRequest
	21, // 29: event.EventService.CreateConfig:input_type -> event.CreateEventConfigRequest
	23, // 30: event.EventService.GetConfig:input_type -> event.GetEventConfigRequest
	25, // 31: event.EventService.UpdateConfig:input_type -> event.UpdateEventConfigRequest
	27, // 32: event.EventService.ApproveEvent:input_type -> event.ApproveEventRequest
	28, // 33: event.EventService.PublishEvent:input_type -> event.PublishEventRequest
	29, // 34: event.EventService.CancelEvent:input_type -> event.CancelEventRequest
	31, // 35: event.EventService.GetEventRoles:input_type -> event.GetEventRolesRequest
	33, // 36: event.EventService.AssignEventRole:input_type -> event.AssignEventRoleRequest
	35, // 37: event.EventService.RemoveEventRole:input_type -> event.RemoveEventRoleRequest
	9,  // 38: event.EventService.Create:output_type -> event.CreateEventResponse
	11, // 39: event.EventService.Update:output_type -> event.UpdateEventResponse
	13, // 40: event.EventService.FindOne:output_type -> event.FindOneEventResponse
	16, // 41: event.EventService.FindMany:output_type -> event.FindManyEventResponse
	19, // 42: event.EventService.List:output_type -> event.ListEventResponse
	36, // 43: event.EventService.Delete:output_type -> google.protobuf.Empty
	22, // 44: event.EventService.CreateConfig:output_type -> event.CreateEventConfigResponse
	24, // 45: event.EventService.GetConfig:output_type -> event.GetEventConfigResponse
	26, // 46: event.EventService.UpdateConfig:output_type -> event.UpdateEventConfigResponse
	36, // 47: event.EventService.ApproveEvent:output_type -> google.protobuf.Empty
	36, // 48: event.EventService.PublishEvent:output_type -> google.protobuf.Empty
	36, // 49: event.EventService.CancelEvent:output_type -> google.protobuf.Empty
	32, // 50: event.EventService.GetEventRoles:output_type -> event.GetEventRolesResponse
	34, // 51: event.EventService.AssignEventRole:output_type -> event.AssignEventRoleResponse
	36, // 52: event.EventService.RemoveEventRole:output_type -> google.protobuf.Empty
	38, // [38:53] is the sub-list for method output_type
	23, // [23:38] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[6].OneofWrappers = []any{}
	file_event_proto_msgTypes[8].OneofWrappers = []any{}
	file_event_proto_msgTypes[12].OneofWrappers = []any{}
	file_event_proto_msgTypes[13].OneofWrappers = []any{}
	file_event_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
